version: 0.2

phases:
  install:
    commands:
     # variables
      - REPOSITORY_URI=635259673755.dkr.ecr.us-east-2.amazonaws.com/demo_microservices
      - ARTIFACT=demo
      - ARTIFACT_TYPE=.jar 
      # - TAG_NAME=$REPOSITORY_URI:$ARTIFACT
      - TAG_NAME=latest
      - echo $AWS_DEFAULT_REGION 
      - echo $ARTIFACT
      - echo $ARTIFACT_TYPE
      - echo $REPOSITORY_URI
      - echo $TAG_NAME  
      # installation
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
      #- apt-get install -y gradle

  pre_build:
    commands:

  build:
    commands:
      - echo Maven Build ...
      - mvn package
      - echo Building the Docker image...  
      - docker build demo_microservices -t .
      - docker tag demo_microservices:$TAG_NAME $REPOSITORY_URI:$TAG_NAME
  post_build:
    commands:
      #- docker tag $REPOSITORY_URI:$ARTIFACT $REPOSITORY_URI:$$ARTIFACT
       #- $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
       - $(aws ecr get-login --region us-east-2 --no-include-email)
       - echo Build completed on `date`
       - echo Pushing the Docker images... $REPOSITORY_URI:$TAG_NAME
       - docker push $REPOSITORY_URI:$TAG_NAME
       #- aws ecs list-services --cluster UngerwECS
       #- aws ecs update-service --cluster UngerwECS --service SpringBootService-Service-XBO2INJQRTEO --task-definition UngerwSpringBootTD
       
artifacts:
     files:
      - imagedefinitions.json  
      - target/demo-0.0.1-SNAPSHOT.jar